.TH mln 1 "May 2013" Manta "Manta Commands"
.SH NAME
.PP
mln \- make link between objects
.SH SYNOPSIS
.PP
\fB\fCmln\fR [OPTION...] TARGET LINK_NAME
.SH DESCRIPTION
.PP
mln creates a link to TARGET with the name LINK_NAME.  Links in Manta are
allowed to be created by pointing at an object only, and are semantically
different than a UNIX link (both hard and soft).  Links in Manta are essentially
a "snapshot".  That is given object \fB\fCA\fR and a link \fB\fCB\fR to \fB\fCA\fR, when \fB\fCA\fR is
overwritten to be \fB\fCA'\fR, \fB\fCB\fR will still return the original value of \fB\fCA\fR\&.
.SH EXAMPLES
.PP
Creates a link from README that snapshots the contents of README.md.
.PP
.RS
.nf
$ mln ~~/stor/README.md ~~/stor/README
.fi
.RE
.SH OPTIONS
.TP
\fB\fC\-a, \-\-account login\fR
Authenticate as account (login name).
.TP
\fB\fC\-h, \-\-help\fR
Print a help message and exit.
.TP
\fB\fC\-i, \-\-insecure\fR
This option explicitly allows "insecure" SSL connections and transfers.  All
SSL connections are attempted to be made secure by using the CA certificate
bundle installed by default.
.TP
\fB\fC\-k, \-\-key fingerprint\fR
Authenticate using the SSH key described by FINGERPRINT.  The key must
either be in \fB\fC~/.ssh\fR or loaded in the SSH agent via \fB\fCssh\-add\fR\&.
.TP
\fB\fC\-\-role=ROLE,ROLE,...\fR
Specify which roles to assume for the request.
.TP
\fB\fC\-\-role\-tag=ROLE,ROLE,...\fR
Set the role tags on the created link.
.TP
\fB\fC\-\-user user\fR
Authenticate as user under account.
.TP
\fB\fC\-u, \-\-url url\fR
Manta base URL (such as \fB\fChttps://manta.us\-east.joyent.com\fR).
.TP
\fB\fC\-v, \-\-verbose\fR
Print debug output to stderr.  Repeat option to increase verbosity.
.SH ENVIRONMENT
.TP
\fB\fCMANTA_USER\fR
In place of \fB\fC\-a, \-\-account\fR\&.
.TP
\fB\fCMANTA_SUBUSER\fR
In place of \fB\fC\-\-user\fR\&.
.TP
\fB\fCMANTA_KEY_ID\fR
In place of \fB\fC\-k, \-\-key\fR\&.
.TP
\fB\fCMANTA_ROLE\fR
In place of \fB\fC\-\-role\fR\&.
.TP
\fB\fCMANTA_URL\fR
In place of \fB\fC\-u, \-\-url\fR\&.
.TP
\fB\fCMANTA_TLS_INSECURE\fR
In place of \fB\fC\-i, \-\-insecure\fR\&.
.PP
The shortcut \fB\fC~~\fR is equivalent to \fB\fC/:login\fR
where \fB\fC:login\fR is the account login name.
.SH DIAGNOSTICS
.PP
When using the \fB\fC\-v\fR option, diagnostics will be sent to stderr in bunyan
output format.  As an example of tracing all information about a request,
try:
.PP
.RS
.nf
$ mln \-vv ~~/stor/foo 2>&1 | bunyan
.fi
.RE
.SH BUGS
.PP
DSA keys do not work when loaded via the SSH agent.
.PP
Report bugs at Github \[la]https://github.com/joyent/node-manta/issues\[ra]
